<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Balance' => '',
    'Create Material' => '',
    'Create Material Type' => '',
    'Create Patient' => '',
    'Create Service' => '',
    'Create Treatment' => '',
    'Create Treatment Time' => '',
    'Create Treatment Type' => '',
    'Create Visit' => '',
    'Delete' => '',
    'Duration' => '',
    'Email' => '',
    'Fk Id Service' => '',
    'Fk Id Treatment Type' => '',
    'Fk Patient' => '',
    'Fk Service Type' => '',
    'Fk User' => '',
    'Id Material' => '',
    'Id Material Type' => '',
    'Id Patient' => '',
    'Id Service' => '',
    'Id Treatment' => '',
    'Id Treatment Time' => '',
    'Id Treatment Type' => '',
    'Id Visit' => '',
    'Info' => '',
    'Make reservation' => '',
    'Material Types' => '',
    'Materials' => '',
    'Name' => '',
    'Patients' => '',
    'Phone' => '',
    'Price' => '',
    'Reset' => '',
    'Room' => '',
    'Save' => '',
    'Search' => '',
    'Services' => '',
    'Start Time' => '',
    'Status' => '',
    'Submit' => '',
    'Surname' => '',
    'The requested page does not exist.' => '',
    'Total Price' => '',
    'Treatment Times' => '',
    'Treatment Types' => '',
    'Treatments' => '',
    'Update' => '',
    'Update Material Type: {name}' => '',
    'Update Material: {name}' => '',
    'Update Patient: {name}' => '',
    'Update Service: {name}' => '',
    'Update Treatment Time: {name}' => '',
    'Update Treatment Type: {name}' => '',
    'Update Treatment: {name}' => '',
    'Update Visit: {name}' => '',
    'Visits' => '',
];
